[package]
name = "dag-cbor"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
async-std = { git = "https://github.com/dvc94ch/async-std" }
async-trait = "0.1"
byteorder = "1.3"
failure = "0.1"
futures-io-preview = { version = "=0.3.0-alpha.18" }
libipld-base = { path = "../base" }

[dev-dependencies]
libipld-macro = { path = "../macro" }
