[package]
name = "libipld-cbor"
version = "0.4.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "ipld cbor codec"
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
byteorder = "1.3.4"
libipld-core = { version = "0.4.0", path = "../core" }
thiserror = "1.0.19"

[dev-dependencies]
libipld-macro = { path = "../macro" }
hex = "0.4.2"
