[package]
name = "dag-cbor"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
byteorder = "1.3.4"
libipld-base = { path = "../base" }
thiserror = "1.0.11"

[dev-dependencies]
libipld-macro = { path = "../macro" }
multihash = "0.10.1"
