[package]
name = "libipld-cbor"
version = "0.9.1"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "ipld cbor codec"
repository = "https://github.com/ipfs-rust/rust-ipld"

[features]
unleashed = ["libipld-core/unleashed"]

[dependencies]
byteorder = "1.3.4"
libipld-core = { version = "0.9.0", path = "../core" }
thiserror = "1.0.22"
unicode-normalization = "0.1.16"

[dev-dependencies]
hex = "0.4.2"
libipld-macro = { path = "../macro" }
multihash = "0.13.2"
